#!/usr/bin/env python
import click

from image_builder.commands.build import build
from image_builder.commands.deploy import deploy


@click.group()
def cli():
    pass


cli.add_command(build)
cli.add_command(deploy)

if __name__ == "__main__":
    cli()
