builders:
  - name: paketobuildpacks/builder-jammy-full
    versions:
      - version: 0.3.431     
      - version: 0.3.414 
      - version: 0.3.397
      - version: 0.3.339
      - version: 0.3.338
      - version: 0.3.317
      - version: 0.3.294
      - version: 0.3.288
  - name: paketobuildpacks/builder-jammy-base
    versions:
      - version: 0.4.398
      - version: 0.4.378
      - version: 0.4.279
      - version: 0.4.278
      - version: 0.4.258
      - version: 0.4.240
      - version: 0.4.239
  - name: paketobuildpacks/builder
    deprecated: true
    versions:
      - version: 0.2.443-full
