on: push

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.python.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "version=$(grep 'python' .tool-versions | sed -e 's/python //')" >> $GITHUB_OUTPUT
        id: python

  lint:
    runs-on: ubuntu-latest
    needs: [versions]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ needs.versions.outputs.python-version }}'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pre-commit run --all

  test:
    runs-on: ubuntu-latest
    needs: [versions]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ needs.versions.outputs.python-version }}'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest
