name: Push Paketo Buildpacks from DockerHub to ECR

on: push

jobs:
  paketo:
    name: Push Paketo Buildpacks from DockerHub to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from DockerHub
        id: pull
        run: |
          TAG=$(curl -s 'https://hub.docker.com/v2/repositories/paketobuildpacks/builder/tags?name=-full&page_size=1' | jq -r '.results[].name')
          echo ${TAG}
          echo "{tag}=${TAG}" >> "$GITHUB_OUTPUT"
      - name: Tag Docker image
        run: |
          echo ${{ steps.pull.outputs.TAG }}
